{"name": "Ошибка при создании одинаковых курьеров", "status": "passed", "description": "Проверяем ошибку при создании курьера с уже существующими данными", "steps": [{"name": "Отправляем запрос на создание пользователя", "status": "passed", "start": 1701283923512, "stop": 1701283923762}, {"name": "Отправляем запрос для пользователя с уже существующими данными", "status": "passed", "start": 1701283923762, "stop": 1701283924030}, {"name": "Пользователя невозможно создать с уже существущими данными.Код ответа - 409, тело ответа - \"Этот логин уже используется. Попробуйте другой.\"", "status": "passed", "start": 1701283924030, "stop": 1701283924030}], "start": 1701283923512, "stop": 1701283924030, "uuid": "c440de54-5f37-4115-b606-9fcb0855afc8", "historyId": "50ebec093ab23e1f5d9397faba9a286a", "testCaseId": "50ebec093ab23e1f5d9397faba9a286a", "fullName": "tests.test_create_courier.TestCreateCourier#test_create_same_courier", "labels": [{"name": "suite", "value": "Создание курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-S15PP4S"}, {"name": "thread", "value": "2544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}